### PR TITLE
feat: added timeout option to avoid long executions. close #37

### LINKED ISSUE #37: Add a timeout option (default 10s) for optimizePeaks
Prevent the system to crash by giving a timeout.

The system should throw if the timeout is reached.

### PR DESCRIPTION
**Pull request by jobo322**
if the execution time reach the timeout the main loop is break and returns the progress

### CODE REVIEW

**Review by lpatiny — CHANGES_REQUESTED** [review]
What is happening if there is only one group ?

I think optimize-peaks does not deal with timeout and it should be added there as well and the timeout forwarded to the optimize method.

**Comment by targos** [comment]
Also, shouldn't it throw an error instead of returning a partial result?

**Comment by jobo322** [comment]
yes, it would be better in the optimization package. I will do the respective changes. thanks

**Comment by lpatiny** [comment]
And as Michael suggested you should throw an error and not return partial resutls.

**Comment by jobo322** [comment]
Hello, I put the timeout options in mljs/levenberg-marquardt [PR](https://github.com/mljs/levenberg-marquardt/pull/35), I am not sure if should be a default value of timeout in this package, I would prefer to pass a default value from GSD.

**Review by lpatiny — APPROVED** [review]

**Pull request merged**
